spring.jpa:
    open-in-view: 'false'
    defer-datasource-initialization: 'true'
#    show-sql: 'true'
    properties:
      hibernate.format_sql: 'true'

spring.task.scheduling.pool.size: 2

management:
  endpoints.web.exposure.include: '*'
  info:
    java.enabled: true
    os.enabled: true
  endpoint.health:
    probes.enabled: true
    show-details: always

springdoc:
  api-docs.path: /openapi/api-docs
  swagger-ui.path: /openapi/swagger

logging.level:
  org.hibernate.type.descriptor.sql: trace

#to use MySQL uncomment mysql-connector-java dependency
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/test
#    username: test
#    password: test
#  jpa.hibernate.ddl-auto: update