package dk.cngroup.fetch.controller;

import dk.cngroup.fetch.entity.Client;
import dk.cngroup.fetch.repository.ClientRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.data.rest.webmvc.PersistentEntityResource;
import org.springframework.data.rest.webmvc.PersistentEntityResourceAssembler;
import org.springframework.data.rest.webmvc.RepositoryRestController;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;

//enhancement of /clients endpoint generated by Spring Data REST
@RequiredArgsConstructor
@RepositoryRestController
public class ClientController {

    final ClientRepository repository;

    //custom method returning loaded entity in Spring HATEOAS way
    @GetMapping("/clients/client-management/{name}")
    public ResponseEntity<PersistentEntityResource> getByName(
            @PathVariable String name,
            PersistentEntityResourceAssembler resourceAssembler) {
        Client client = repository.findClientByUserName(name);
        return ResponseEntity.ok(resourceAssembler.toFullResource(client));
    }
}