package dk.cngroup.fetch.controller

import dk.cngroup.fetch.entity.ClientRepository
import org.springframework.data.rest.webmvc.PersistentEntityResource
import org.springframework.data.rest.webmvc.PersistentEntityResourceAssembler
import org.springframework.data.rest.webmvc.RepositoryRestController
import org.springframework.http.ResponseEntity
import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.PathVariable

//enhancement of /clients endpoint generated by Spring Data REST
@RepositoryRestController
class ClientController(private val repository: ClientRepository) {

    //custom method returning loaded entity in Spring HATEOAS way
    @GetMapping("/clients/client-management/{username}")
    fun getByName(
        @PathVariable username: String?,
        resourceAssembler: PersistentEntityResourceAssembler
    ): ResponseEntity<PersistentEntityResource> {
        val client = repository.findClientByUserName(username)
        return ResponseEntity.ok(resourceAssembler.toFullResource(client))
    }
}