package dk.cngroup.wishlist.controller

import dk.cngroup.wishlist.entity.ClientRepository
import org.springframework.data.rest.webmvc.PersistentEntityResource
import org.springframework.data.rest.webmvc.PersistentEntityResourceAssembler
import org.springframework.data.rest.webmvc.RepositoryRestController
import org.springframework.http.ResponseEntity
import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.RequestParam

//enhancement of /clients endpoint generated by Spring Data REST
@RepositoryRestController
class ClientController(private val repository: ClientRepository) {

    //custom method returning loaded entity in Spring HATEOAS way
    @GetMapping("/clients/search/findByUserName")
    fun getByName(
        @RequestParam userName: String,
        resourceAssembler: PersistentEntityResourceAssembler
    ): ResponseEntity<PersistentEntityResource> {
        val client = repository.findClientByUserName(userName)
        return ResponseEntity.ok(resourceAssembler.toFullResource(client))
    }
}