package dk.cngroup.wishlist.controller;

import dk.cngroup.wishlist.entity.Client;
import dk.cngroup.wishlist.repository.ClientRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.data.rest.webmvc.PersistentEntityResource;
import org.springframework.data.rest.webmvc.PersistentEntityResourceAssembler;
import org.springframework.data.rest.webmvc.RepositoryRestController;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;

// enhancement of /clients endpoint generated by Spring Data REST
@RequiredArgsConstructor
@RepositoryRestController
public class ClientController {

    final ClientRepository repository;

    // custom method returning loaded entity in Spring HATEOAS way
    @GetMapping("/clients/search/findByUserName")
    public ResponseEntity<PersistentEntityResource> getByName(
            @RequestParam String userName,
            PersistentEntityResourceAssembler resourceAssembler) {
        Client client = repository.findClientByUserName(userName);
        return ResponseEntity.ok(resourceAssembler.toFullResource(client));
    }
}